name: om
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.2.1
  cupertino_icons: ^1.0.8
  flutter_audio_capture: ^1.1.11
  scidart: ^0.0.2-dev.12
  permission_handler: ^11.0.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  number_inc_dec: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^2.3.0
  flutter_lints: ^5.0.0

executables:
  ffigen:

flutter:
  uses-material-design: true

  assets:
    - assets/images/background_images/background1.jpg
